version: '3'

services:
  postgres:
    image: postgres:12.2-alpine
    container_name: gobarber_postgres
    # restart: always
    ports:
      - 5432:5432
    command: postgres -c idle_in_transaction_session_timeout='1min'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - backend
  mongo:
    image: mongo
    container_name: gobarber_mongo
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: mongo!
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/var/lib/mongodb/data
    networks:
      - backend
  redis:
    image: redis:alpine
    container_name: gobarber_redis
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/var/lib/redis/data
    networks:
      - backend

networks:
  backend:
    driver: bridge
